# Generated by Django 3.2 on 2021-04-12 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='privateKey',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='privateKey'),
            preserve_default=False,
        ),
    ]
