# Generated by Django 3.2 on 2021-04-10 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0002_alter_arizakaydi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizakaydi',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ariza', to=settings.AUTH_USER_MODEL),
        ),
    ]
